### ISSUE TITLE
Add image as an overlay on top of the Camera image

### ISSUE THREAD

**Issue by ServusJon** [BradLarson/GPUImage2#109]
How can I add image as an overlay on top of the camera image? I don't get it to work :-(

**Comment by nateemma** [comment]
You use one of the blend filters. OverlayBlend is probably the simplest.

The code would be something like:

  let image  = UIImage(named: "xxx.png")
  let blendInput = PictureInput(image:image!)
  let opacityFilter = OpacityAdjustment()
  let filter = OverlayBlend()
  opacityFilter.opacity = 0.8

  blendInput! --> opacityFilter! --> filter!
  camera! --> filter! --> renderView!
  blendInput?.processImage()

Where xxx.png would need be part of your project, and obviously you can name it whatever you want. The Opacity filter lets you control the amount of the blending

**Comment by ServusJon** [comment]
Thanks @nateemma!
And what if I want to do it on the live camera image?

**Comment by nateemma** [comment]
That is the code for adding it to the live image. The 'camera' variable is a GPUImage class of type 'Camera', allocated something like:

camera =  Camera(sessionPreset:AVCaptureSessionPresetPhoto, location:.backFacing)

**Comment by ServusJon** [comment]
When I do this my image remains white. :-(
processImage is also not available…


    let renderView = RenderView()
    var camera:Camera!
    
    lazy var lookupFilter = LookupFilter()
    
    let filter = OverlayBlend()
    let opacityFilter = OpacityAdjustment()
    var blendInput:PictureInput?



        lookupFilter.lookupImage = PictureInput(imageName: "fuji800.png")
        
        blendInput = PictureInput(imageName: "fuji800.png")

        opacityFilter.opacity = 0.1
        
     

           camera = try Camera(sessionPreset:AVCaptureSessionPresetPhoto)
            
            blendInput! --> opacityFilter --> filter
            camera --> lookupFilter --> filter --> renderView
            camera.startCapture()

**Comment by nateemma** [comment]
Have you tried it without the lookupFilter? Is fuji800.png a valid lookup image (see description of LookupFilter)?

Also, check that the PictureInput is not null (i.e. that it found the image OK). Sometimes you have to do a  'clean' after adding an image to the project

**Comment by ServusJon** [comment]
Tried it without lookupfilter. No difference…
The lookupimage is valid.
Cleaned the project.

Still not sure if I should use GPUImage 1 instead of 2.

**Comment by nateemma** [comment]
GPUImage 1 is an Objective C library, so you should be using GPUImage2

Are you running on the simulator or a real device? The camera is not supported in the simulator

**Comment by ServusJon** [comment]
This makes me wonder:
https://github.com/BradLarson/GPUImage2#capturing-and-filtering-a-still-photo <https://github.com/BradLarson/GPUImage2#capturing-and-filtering-a-still-photo>


This is my project:
https://www.dropbox.com/s/p1khz7aoc52w554/filtercam.zip?dl=0

I tested it on my device

**Comment by zubco** [comment]
@ServusJon , you never called for `blendInput?.processImage()`.
So, your code should be smth like that:
            
```
            camera = try Camera(sessionPreset:AVCaptureSessionPresetPhoto)
            
            blendInput! --> opacityFilter --> filter
            camera --> filter --> renderView
            blendInput?.processImage()
            
            camera.startCapture()
```

**Comment by ServusJon** [comment]
@zubco Thank you! I was missing .processImage

How could I save an image from my camera (https://github.com/BradLarson/GPUImage2/issues/108)?

**Comment by zubco** [comment]
@ServusJon this one you can find in documentation.

> Capturing an image from video.

`filter.saveNextFrameToURL(url, format:.PNG)`

**Comment by BradLarson** [comment]
As zubco stated, the only way that blendInput would be able to provide its image to the rest of the filter chain is through calling processImage() on it. 

You're also probably not going to want to use the same image for blending as for your lookup, because lookup images have a very specific square format and I doubt you want that to be overlaid on your video.

**Comment by ServusJon** [comment]
The one image was just a test image 😉

And what if I am using Camera(sessionPreset:AVCaptureSessionPresetPhoto)? Do I still do this?
filter.saveNextFrameToURL(url, format:.PNG)

Thank you guys!

**Comment by gaming-hacker** [comment]
can't you just dump out a raw iimage and then use LUTs to post process?
