### ISSUE TITLE
GPUImageRawDataOutput and newFrameAvailableBlock

### ISSUE THREAD

**Issue by omarojo** [BradLarson/GPUImage2#111]
Im trying to extract the **rawBytesForImage** and **bytesPerRowInOutput** to create a CVPixelBuffer on each new available frame coming from GPUImage. 

The following is what I do in GPUImage for Objc, how can I do the same but in **GPUImage 2 in Swift** ?

self.rawG8OutputTarget = [[GPUImageRawDataOutput alloc] initWithImageSize: aspectSize resultsInBGRAFormat:YES];

[filterChain.output addTarget:self.rawG8OutputTarget];

__weak GPUImageRawDataOutput *weakRawOutput = self.rawG8OutputTarget;
[self.rawG8OutputTarget setNewFrameAvailableBlock:^{
    GLubyte *outputBytes = [weakRawOutput rawBytesForImage];
    NSInteger bytesPerRow = [weakRawOutput bytesPerRowInOutput];
    //I use this variables to create the image to be streamed.
}];

**Comment by BradLarson** [comment]
Yes, use the RawDataOutput and set its dataAvailableCallback to get the bytes on each frame.

**Comment by omarojo** [comment]
But how do I know the * bytesPerRowInOutput* ?

**Comment by omarojo** [comment]
I modified the class RawDataOutput.swift from GPUImage2 framework
on this line:
```
glReadPixels(0, 0, framebuffer.size.width, framebuffer.size.height, GLenum(GL_RGBA), GLenum(GL_UNSIGNED_BYTE), &data)
```

instead of GL_RGBA, I changed it to GL_BGRA. 

With that now my CVPixelbuffer that uses 'kCVPixelFormatType_32BGRA' works great.
If I tried to use 'kCVPixelFormatType_32RGBA' to create it, it would fail. 
Apparently ```CVPixelBufferCreateWithBytes``` cant be used with ```kCVPixelFormatType_32RGBA```

Im I okay doing this change in GPUImage framework ? or is it by design ? 

Also I still need the size of the frame or at least the *bytesPerRowInOutput* when data is sent back.

**Comment by cagkanciloglu** [comment]
hey @omarojo did find the solution to your problem?
I am trying to do a similar thing.

**Comment by WillieWu** [comment]
hey @omarojo How to solve the second problem？pixelbuffer has a blue shade

**Comment by omarojo** [comment]
@WillieWu My solution is posted above.

**Comment by WillieWu** [comment]
@omarojo Oh, I see it. Thank you very much
