### ISSUE TITLE
Is there functionality to use a movie file with Chromakey instead of just an image? 

### ISSUE THREAD

**Issue by danicejewishboy** [BradLarson/GPUImage2#118]
Hi,
I am looking to add a green screen part of my app and it would be awesome if I could use videos on the green screen instead of just an image in the background. Is this possible? Amazing work though! 

Best,
Eric

**Comment by BradLarson** [comment]
Yes, the chroma key blend (like all the blends) works with either an image or video source for each input. You can use a video file in place of the still image, and it should work just fine. If it doesn't, that would be a bug.

**Comment by danicejewishboy** [comment]
Thank you very much!
