### ISSUE TITLE
Is it possible to loop a video that is playing?

### ISSUE THREAD

**Issue by SoundandStuff** [BradLarson/GPUImage2#119]
HI, 
I am looking to repeat my video once it finishes. Is that possible?

**Comment by danicejewishboy** [comment]
I never found a working solution, but I did find that in order to generate a loop, it requires a new AVAsset every loop. My method never seemed to work unfortunately, but if anyone wants to see my work adding to Movie-input, let me know.

**Comment by Limon-O-O** [comment]
Yes, you must create a new `AVAssetReader` every loop.

**Comment by danicejewishboy** [comment]
Limon did you ever figure out how to loop on movie input? I am guessing I am going to need to look up AVPlayerItem and how to use that with AVAssets. If I figure it out I will happily add it to the code.

**Comment by Limon-O-O** [comment]
```swift
public func start() {
    self.assetReader = generateAssetReader(asset: asset, readAudio: readAudio, videoOutputSettings: videoOutputSettings, audioOutputSettings: audioOutputSettings)

.....
.....
.....

    if assetReader.status == .completed {
        assetReader.cancelReading()
        self.assetReader = nil
        if self.loop {
            self.start()
        } else {
            self.endProcessing()
        }
    }
}
```

**Comment by danicejewishboy** [comment]
So just to be clear you made a function called generateAssetReader somewhere in your code? Also on my screen I can not assign assign self.assetReader = nil. I think I am probably missing something vital.

**Comment by SoundandStuff** [comment]
I found a way of doing it. The only issue is it isn't as pretty as it is when I don't loop it or only have it loop once. Would it be OK if I emailed you the code and we could optimize it together @Limon-O-O and put in a pull request?

**Comment by PicooRicoo** [comment]
Did you guys found a solution to this? I'm in the same problem.

**Comment by PicooRicoo** [comment]
Yes! I made it! And it is smooth as a snowflake LOL.

So I made the famous generateAssetReader() @SoundandStuff  was asking for, this is my final code.

`public func createReader() -> AVAssetReader
    {
        var assetRead:AVAssetReader!
        do{
            assetRead = try AVAssetReader.init(asset: self.asset)
            
            let outputSettings:[String:AnyObject] = [(kCVPixelBufferPixelFormatTypeKey as String):NSNumber(value:Int32(kCVPixelFormatType_420YpCbCr8BiPlanarFullRange))]
            let readerVideoTrackOutput = AVAssetReaderTrackOutput(track:self.asset.tracks(withMediaType: AVMediaTypeVideo)[0], outputSettings:outputSettings)
            readerVideoTrackOutput.alwaysCopiesSampleData = false
            
            assetRead.add(readerVideoTrackOutput)
        }catch{
            
        }
        
        return assetRead
    }

    public func start() {
        self.assetReader = createReader()
        asset.loadValuesAsynchronously(forKeys:["tracks"], completionHandler:{
            DispatchQueue.global(priority:DispatchQueue.GlobalQueuePriority.default).async(execute: {
                guard (self.asset.statusOfValue(forKey: "tracks", error:nil) == .loaded) else { return }

                guard self.assetReader.startReading() else {
                    print("Couldn't start reading")
                    return
                }
                
                var readerVideoTrackOutput:AVAssetReaderOutput? = nil;
                
                for output in self.assetReader.outputs {
                    if(output.mediaType == AVMediaTypeVideo) {
                        readerVideoTrackOutput = output;
                    }
                }
                
                while (self.assetReader.status == .reading) {
                    self.readNextVideoFrame(from:readerVideoTrackOutput!)
                }
                
                if (self.assetReader.status == .completed) {
                    self.assetReader.cancelReading()
                    
                    if (self.loop) {
                        // TODO: Restart movie processing
                        self.start()
                    } else {
                        self.endProcessing()
                    }
                }
            })
        })
    }`

**Comment by SoundandStuff** [comment]
Lol wow you solved the problem! You're solution runs much more smoothly than mine.

**Comment by SoundandStuff** [comment]
Your*
