### ISSUE TITLE
Using Obj-C GPUImage Filters

### ISSUE THREAD

**Issue by weixiyen** [BradLarson/GPUImage2#14]
Is there a way to use custom objective-c gpuimage filters in GPUImage2?

**Comment by BradLarson** [comment]
You'll have to do a few things to port across older Objective-C custom filters to GPUImage 2. First, the shaders will need to be broken out into standalone files, or inlined into Swift string constants.

Your filter will most likely be a subclass of BasicOperation, which can take in an arbitrary number of inputs now. I recommend using one of the existing Swift filter subclasses as a template and changing things out to match your new filter.

You'll need to update any properties that set uniforms to use the new syntax:

```swift
public var brightness:Float = 0.0 { didSet { uniformSettings["brightness"] = brightness } }
```

where the portion in quotes above is the name of the uniform you're setting in your shader.

Looks like I had missed the need for a couple of public initializers in my base classes, but you wouldn't have needed those if you were subclassing from BasicOperation.
