### ISSUE TITLE
GaussianBlur (and many more!) crashing on Release Builds of FilterShowcases

### ISSUE THREAD

**Issue by batilc1** [BradLarson/GPUImage2#143]
It works normal while working on Debug builds. If you get a Release build, the app crashes as soon as GaussianBlur is inserted into the camera pipeline.

Note that, same thing goes for many more effects. Some of the notable ones are:
- Gaussian Blur
- Canny Edge Detector
- Harris Corner Detector
- SoftElegance Filter

The complete list is below:
UnsharpMask
SoftElegance
CannyEdgeDetection
HarrisCornerDetection
NobleCornerDetection
ShiThomasiFeatureDetection
SmoothToon
TiltShift
GaussianBlur
iOS7Blur
SphereRefraction
GlassSphere

**Comment by BradLarson** [comment]
Did this just start happening with Xcode 8.3? I can reproduce the crash, but I don't recall this happening before. It looks like a potential early deallocation of a Swift string before or during shader compilation, from the traces I'm seeing and the fact that it only happens during release builds.

Not quite sure why it's happening, and if it just started with Xcode 8.3 it might be related to the new Swift compiler.

**Comment by wallerdev** [comment]
Also seeing this after upgrading to xcode 8.3

**Comment by batilc1** [comment]
Yes, this issue got raised while using the new Swift compiler with Xcode 8.3. Unfortunately before 8.3, I either compiled debug builds or used filters not on the list above; so I cannot say if its related to a previous release of Xcode or not.

**Comment by batilc1** [comment]
Actually, I noticed that almost all of the items in the list above are directly using GaussianBlur. Only CannyEdgeDetector uses a SingleComponentGaussianBlur which I expect to have the same issue.

After replacing GaussianBlur with BoxBlur in the rest of the items in the list, I can successfully use every filter again except GaussianBlur and CannyEdgeDetector

**Comment by BradLarson** [comment]
I believe that this is happening with Gaussian blurs due to the fact that they don't use hardcoded shaders, the shaders are created on-demand for a given blur size. The functions that do this output a Swift string which is compiled into the shader program.

Somehow, this string looks like it's being deallocated early after being returned from the functions that generate it, but before the shader compilation process is finished. I've seen this before with Swift strings and overly aggressive optimizations in release builds in previous compiler versions, so I'll see if there's a workaround that can be used to prevent this until the compiler is fixed.

**Comment by rpranata** [comment]
Is there an update on this? 

We tried adding the [`@_semantics(“optimize.sil.never”)`](http://apple-swift.readthedocs.io/en/latest/HighLevelSILOptimizations.html#optimize-semantics-attribute) [here](https://github.com/BradLarson/GPUImage2/blob/858b01fc2fd7d1e07a697e8dc6c3a119e4773ef1/framework/Source/Operations/GaussianBlur.swift#L138) but it didnt work.

However, turning off Optimizations(`-Onone`) is confirmed to work.

**Comment by wallerdev** [comment]
@rpranata I was able to get it working by adding the  @_semantics(“optimize.sil.never”) on line 122: https://github.com/BradLarson/GPUImage2/blob/858b01fc2fd7d1e07a697e8dc6c3a119e4773ef1/framework/Source/Operations/GaussianBlur.swift#L122

**Comment by wallerdev** [comment]
Opened a PR with a fix for people experiencing this issue.

**Comment by BradLarson** [comment]
I can confirm that the above pull request seems to fix this, and may not be related to Strings as I thought. I've filed this as a compiler bug under Radar number 31587960, with this as a test case.

**Comment by rpranata** [comment]
When I was debugging yesterday, I found out that the prematurely deallocated object was indeed the string here https://github.com/BradLarson/GPUImage2/blob/858b01fc2fd7d1e07a697e8dc6c3a119e4773ef1/framework/Source/Operations/GaussianBlur.swift#L152 which makes me also believe that it has something to do with the String but when putting `@_semantics(“optimize.sil.never”)` to that method didn't fix it, I started to wonder what else could be wrong. 

Thanks for the fix @wallerdev!

**Comment by BradLarson** [comment]
As a longer-term fix, I checked against the latest Swift 3.1 nightly, and this bug was fixed there. I assume that will be the case for the next public release, so this is only a temporary thing for this build of Xcode 8.3.

**Comment by mt-rpranata** [comment]
I have recently experienced this issue again on a release build. 

It crashed under Release build as soon as `Canny Edge Detector` is being added, the exact line that is crashed is

https://github.com/BradLarson/GPUImage2/blob/master/framework/Source/OpenGLContext_Shared.swift#L25

Seems like `shaderCache` is being deallocated early?

Any ideas @BradLarson @wallerdev ?

**Comment by mt-franco** [comment]
@mt-rpranata I think this PR fixes it:
https://github.com/BradLarson/GPUImage2/pull/305/files
