### ISSUE TITLE
How to change the intensity of filters applied ?

### ISSUE THREAD

**Issue by 1792Anurag** [BradLarson/GPUImage2#144]
Hi, 

Can anyone please guide me how to change the filter intensity applied to a still image with a uislider using GPU image 2 on filters like Hue, brightness, vignette, saturation etc.
It would be a great help , if possible please demonstrate this with a code.
Thank you in advance.

**Comment by BradLarson** [comment]
All you have to do is take the input from your slider, map that to a range of values for whatever filter parameter you want to adjust, and set that parameter on a change of slider. If you're doing this on live video, the change will be displayed immediately. If you're using a PictureInput, you'll need to call processImage() on it to get the update image to propagate through the filter chain.

**Comment by 1792Anurag** [comment]
Thank you Brad .
