### ISSUE TITLE
Switching between camera.

### ISSUE THREAD

**Issue by 1792Anurag** [BradLarson/GPUImage2#145]
Hi, 

How to switch between the front and back camera with a single button and simultaneously managing the orientation of the render view .
Demonstration with a code will be high helpful.

Any Help will be appreciated , thank you in advance.

**Comment by 1792Anurag** [comment]
Using GPUImage2

**Comment by BradLarson** [comment]
I'm sorry, but I think you misunderstand the purpose of GitHub issues.

**Comment by 1792Anurag** [comment]
That's OK :) thank you.
