### ISSUE TITLE
XCode errors out when using ImageConsumer

### ISSUE THREAD

**Issue by weixiyen** [BradLarson/GPUImage2#15]
Hi Brad, 

I'm getting this error when trying to set up my own class that conforms to ImageConsumer:

"Source Container cannot be constructed because it has no accessible initializers"

<img width="730" alt="screenshot 2016-05-05 22 46 04" src="https://cloud.githubusercontent.com/assets/59597/15065733/6c5f798a-1317-11e6-97dd-6eabfd08e29d.png">

**Comment by zubco** [comment]
PR [#16](https://github.com/BradLarson/GPUImage2/pull/16) should fix that.

**Comment by BradLarson** [comment]
This should be fixed now.
