### ISSUE TITLE
MotionDetector with CMSampleBuffer

### ISSUE THREAD

**Issue by dimohamdy** [BradLarson/GPUImage2#150]
How i can use MotionDetector with didCaptureBuffer(_ sampleBuffer: CMSampleBuffer) ?

**Comment by BradLarson** [comment]
I don't think you can, at least not easily. It requires a texture-backed framebuffer as input (as do almost all GPUImage operations). Is there a reason why you'd want to handle the sample buffers yourself, as opposed to just using a Camera, Movie, or PictureInput instance?

**Comment by dimohamdy** [comment]
i already have code that  shared the camera between multi ViewController i don't want to change this code

**Comment by BradLarson** [comment]
It's honestly not that hard to use a new Camera instance. It's just a couple of lines of code.
