### ISSUE TITLE
Bug in BoxBlur shader?

### ISSUE THREAD

**Issue by olivierpascal** [BradLarson/GPUImage2#154]
BoxBlur.swift, lines 35-36:
```
shaderString += "blurCoordinates[\((currentOptimizedOffset * 2) + 1)] = inputTextureCoordinate.xy + singleStepOffset * \(optimizedOffset);\n"
shaderString += "blurCoordinates[\((currentOptimizedOffset * 2) + 2)] = inputTextureCoordinate.xy + singleStepOffset * \(optimizedOffset);\n"
````
Shouldn't the 2nd offset be negative?

**Comment by olivierpascal** [comment]
@BradLarson if you confirm I can prepare a pull request :)

**Comment by BradLarson** [comment]
So sorry it took so long to get back to you on this, but you're right, I did mistakenly copy the wrong line there. This should be fixed in the latest commit.

Thanks for pointing this out.
