### ISSUE TITLE
Could we uniform the swift code style?

### ISSUE THREAD

**Issue by zubco** [BradLarson/GPUImage2#159]
Hi @BradLarson, I wonder if it is possible to uniform GPUImage2 swift code style?
I suggest to use some basic style like [GitHub one](https://github.com/github/swift-style-guide).

I am ready to contribute on that, sure with some of your help.
If you are in accord with that proposal, I will split the changes in some steps (smaller commits) and could start working on it:
1. ../framework/Source/iOS/
2. ../framework/Source/Mac/
3. ../framework/Source/Linux/ (Your help will be required, probably)
4. ../framework/Source/Operations/
5. ../framework/Source/ (universal code base)
6. ../examples/iOS/
7. ../examples/Mac/
8. ../examples/Linux-../
9. Readme file, to match the changes above.

**Comment by BradLarson** [comment]
In general, I maintain my own style, informed by the general Swift style guidelines but not completely beholden to them. There are some small areas that I believe deviating from standard style produces more readable code. I do try to be consistent with how things are formatted in my Swift projects, though.

I'll admit that I haven't fully renamed the functions to match the newer Swift 3 style (imageForInput -> image(for: input), etc.).

In what areas do you feel the style of the project is lacking or inconsistent?

**Comment by zubco** [comment]
In general, thank you very much for your amazing work ! 👍 
Yes, you are right. Majority of code is written by you and it is pretty consistent, thank you for that! But different people tend to have some deviations at writing code, that is absolutely normal for developers :) . So my suggestion was to provide a reference point for contributors, in long term that should be beneficial for the project. 

Beside Swift 3 naming style you pointed out, I wonder if some of that points could be changed:
1. Associate the colon with the identifier, when specifying a type? 
```
public class TextureInput: ImageSource { ... }

let textureFramebuffer: Framebuffer

public init(texture: GLuint, size: Size, orientation: ImageOrientation = .portrait) { ... }
```

I will quote:

Rationale: The type specifier is saying something about the identifier so it should be positioned with it.

That should be available for dictionaries, also:

`var localSettings: [String: AnyObject]`

2. Are some variables setup/ functions calls sometimes overwhelming long, a more vertical approach with few newlines could help ?
 `public var temperature:Float = 5000.0 { didSet { uniformSettings["temperature"] = temperature < 5000.0 ? 0.0004 * (temperature - 5000.0) : 0.00006 * (temperature - 5000.0) } }`

Sure they are handy, but sometime they are hard quickly to
 understand.

3. Implicit getters on read-only properties?
```
public var asCMTime: CMTime {
    return CMTimeMakeWithEpoch(value, timescale, epoch)
}
```
Is more concise vs:
```
public var asCMTime: CMTime {
    get {
         return CMTimeMakeWithEpoch(value, timescale, epoch)
    }
}
```

That are a few that could be considered in my opinion.

P.S.: That could be a problem only for me, the pleb who likes sometime to look in deep to understand how things work. Let me know what you think, thank you.

**Comment by zubco** [comment]
Hi @BradLarson. If what I commented above doesn't make sense for you, then you can close the issue.
