### ISSUE TITLE
Changing live filter not working

### ISSUE THREAD

**Issue by hardik99** [BradLarson/GPUImage2#162]
```
        do {
            movie = try MovieInput(asset: asset, playAtActualSpeed: true, loop: true)
            movie --> LowPassFilter() --> objVideoPlayerView
            movie.runBenchmark = true
            movie.start()
        } catch {
            print("Couldn't process movie with error: \(error)")
        }

```

I have applied below code to change filter:
```
        movie.removeAllTargets()
        movie --> SketchFilter() --> objVideoPlayerView

```
I am not able to filter on video.

**Comment by BradLarson** [comment]
You also have to break the connection between the low pass filter and your objVideoPlayerView. You need to store that as an instance variable and add removeAllTargets() for it before you set up your processing pipeline again.

**Comment by henvyluk** [comment]
@BradLarson I am not understand how to break the connection between the low pass filter and your objVideoPlayerView?

**Comment by hardik99** [comment]
**Declare below varialble global :** 
    var movie:MovieInput!
    var objLowPassfilter: SmoothToonFilter!
    var objSketchFilter: SketchFilter!

**And do below things:**

    func gpuFilters () -> Void {
        do {
            movie = try MovieInput(asset: session.assetRepresentingSegments(), playAtActualSpeed: true, loop: true)
            
            objLowPassfilter = SmoothToonFilter()
            movie --> objLowPassfilter --> objVideoPlayerView
            movie.runBenchmark = true
            movie.start()
        } catch {
            print("Couldn't process movie with error: \(error)")
        }
    }
    
    func applyGPUFilters(selectedFilter: Int) -> Void {
        movie.removeAllTargets()
        objLowPassfilter.removeAllTargets()
        
        do {
            movie = try MovieInput(asset: session.assetRepresentingSegments(), playAtActualSpeed: true, loop: true)
            objSketchFilter = SketchFilter()
            movie --> objSketchFilter --> objVideoPlayerView
            movie.runBenchmark = true
            movie.start()
        } catch {
            print("Couldn't process movie with error: \(error)")
        }
    }
