### ISSUE TITLE
GPUImage2 issues related to using custom filters

### ISSUE THREAD

**Issue by henvyluk** [BradLarson/GPUImage2#163]
Hello, I do not know where it is appropriate to ask such a question, I recently was doing something related to the filter, and of course no doubt, GPUImage and GPUImage2, I had the previous reference obje-c project, which uses a GPUImage It is written by OpenGL Shading language (GLSL) Fragment shader string macro point, as well as physical picture xxx.png application file is assigned to GPUImagePicture Bundle in a subclass, to complete the rendering filter in such a way, but I my swift project, no doubt GPUImage2, I can not find the right way to deal with, I now have the resources or several xxx.png as well as with the corresponding Fragment Shader file, I see you in GPUImage2 official website the assertion that loaded directly by .fsh files, but the effect is not what I want, because now .fsh file or obje-c sample project, I guess the reason is the lack of xxx.png filter, so I think ask is how in GPUImage2 through my current resource loading filter it, I hope this expression can be understood, it has been plagued by the problem of non I hope you can give me some help, thank you very much!

**Comment by BradLarson** [comment]
Honestly, I can't understand what you're asking here.
