### ISSUE TITLE
iOS, OpenGLContext nil crash, XC9 beta

### ISSUE THREAD

**Issue by dsowsy** [BradLarson/GPUImage2#164]
I've experienced a nil crash on imageProcessingShareGroup in OpenGLContext.swift
and decided to eagerly instantiate up above.
```
var imageProcessingShareGroup:EAGLSharegroup? = nil
```
with
```
var imageProcessingShareGroup:EAGLSharegroup = EAGLSharegroup()
```

Does this make sense?

**Comment by BradLarson** [comment]
The real problem is that I'm not handling a nil sharegroup properly now that the API expects a non-nil value for EAGLContext's init. 

I've pushed a commit that I had locally when testing out Xcode 9. Try that and see if that handles this correctly.

**Comment by dsowsy** [comment]
Works for my devices! :thumbsup:
