### ISSUE TITLE
How to use OpenGL ES shader files and color mapping files to do custom filter?

### ISSUE THREAD

**Issue by henvyluk** [BradLarson/GPUImage2#166]
How to use OpenGL ES shader files and color mapping files to do custom filter? Hope to give me some guidance,I really do not know how to handle it.

**Comment by BradLarson** [comment]
This is way too broad to answer. It's like asking how to write a program, without specifying what you want that program to do.

It is also not a bug or issue with the framework. Sorry, but you're going to need to refine this question to ask something more targeted and ask it elsewhere.
