### ISSUE TITLE
Cant't build on Xcode 8.3.1

### ISSUE THREAD

**Issue by yashpixster** [BradLarson/GPUImage2#170]
![screen shot 2017-06-23 at 5 32 23 pm](https://user-images.githubusercontent.com/28924353/27481395-fa87ab98-5839-11e7-879b-90616cd6e97e.png)
Hi, Sir

i'm getting this error --> Command/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

Thank you.

**Comment by BradLarson** [comment]
This looks like a problem with how you're importing the framework. It looks like you're somehow trying to compile the Swift package manager files for the Linux camera code. Something with how you've added this to your application is broken.

The framework builds just fine under Xcode 8.3.
