### ISSUE TITLE
ShaderConverter Error

### ISSUE THREAD

**Issue by metpb** [BradLarson/GPUImage2#171]
Hi, I followed and used `ShaderConverter` to convert my local shader files to inlined strings.
It converted and generated a `ConvertedShaders_GL.swift` & `ConvertedShaders_GLES.swift` respectively, but few (most) of the string constants are throwing an error `[Unprintable ASCII character found in source file]`

FYI, I checked but couldn't find any invalid characters. The error doesn't show up when I manually inline the shader program to strings.

Any known fix or workaround would be super helpful. Thanks

**Comment by BradLarson** [comment]
I've had this happen a few times, and I think it was usually due to the presence of tabs instead of spaces in the indentation of the shader files. Try converting indentation to spaces to remove all tabs, and strip whitespace from the ends of your lines.

**Comment by metpb** [comment]
The errors are gone, but somehow the filters aren't being applied.

By the way, I forgot to mention that I converted shader programs with `.glsl` extension to `.fsh` before running the script. Will it work? Because `ShaderConverter` won't take files with `.glsl` extensions.
