### ISSUE TITLE
OperationGroup not working

### ISSUE THREAD

**Issue by kietho123** [BradLarson/GPUImage2#19]
Hi Brad,

I'm trying your sample code:
let boxBlur = BoxBlur()
let contrast = ContrastAdjustment()
let myGroup = OperationGroup()
myGroup.configureGroup{input, output in
    input --> self.boxBlur --> self.contrast --> output
}

"let myGroup = OperationGroup()" is always giving me the error as "'OperationGroup' cannot be constructed because it has no accessible initializers". Not sure if I missed any thing or the class has not been completed. Thanks.

**Comment by BradLarson** [comment]
That was simply because I forgot to add a public init() to the OperationGroup class. This should be fixed in the latest commit.

**Comment by kietho123** [comment]
Thanks Brad for replying quickly. Your work is really inspired.
