### ISSUE TITLE
Beautify Face

### ISSUE THREAD

**Issue by chengkaizone** [BradLarson/GPUImage2#198]
Whether there is a beauty filter ?

**Comment by BradLarson** [comment]
That could be any number of things.

Beauty is in the eye of the beholder.

**Comment by ep372** [comment]
Ahah I love your answer Brad!
I was looking for "a beauty filter" as well to reproduce Snapchat one. No success. I think it is not as easy as sepia or whatever. I think there is face detection with hard work behind the scene.
I finally use MissEtikate filter to achieve this but not a real beautifying filter.
