### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by Sumit-2singh** [BradLarson/GPUImage2#207]
hi,
Actually, my need  is  to capture image from camera  and for this whenever i call this function " public func synchronousImageCapture() -> UIImage " for get image.
app going to crash

**Comment by Sumit-2singh** [comment]
hi @BradLarson  is in future have your any plan , to give feature for take image with filter in GPUImage2(Swift version) ?

**Comment by ep372** [comment]
Hi,
It is not direclty implemented for now but you can use what is discribed on the Readme (cf Capturing an image from video)
`filter.saveNextFrameToURL(url, format:.PNG)`
to capture and store directly the picture to FS.

Or you can use a PictureOutput on your pipeline to process data and transform to UIImage.
