### ISSUE TITLE
Errors compiling the framework.............

### ISSUE THREAD

**Issue by cloyOnGit** [BradLarson/GPUImage2#21]
Pipeline.swift could not compile...... I added the GPUImage-iOS.xcodeproj as a framework in Target Dependency and also in Link Binary with Libraries..........was there something else to be done besides that too....

**Comment by BradLarson** [comment]
What version of Xcode are you using? This needs Swift 2.2 (Xcode 7.3). What compiler errors did you see?

**Comment by cloyOnGit** [comment]
I m using swift 2.0....and xcode 7.0........so i just need to update..... Thanks Brad
