### ISSUE TITLE
New project choosing between GPUImage1 and GPUImage2

### ISSUE THREAD

**Issue by weepy** [BradLarson/GPUImage2#219]
Hiya - I'm starting a new iPhone project. --- would you recommend using GPUImage or GPUImage2 (happy with Swift or ObjectiveC). You seem to be actively developing both - so a bit difficult to tell!

**Comment by BradLarson** [comment]
The Objective-C project is no longer being actively maintained, and I honestly haven't had much time to work on the Swift project lately, as well. The Swift project is better organized and easier to use, but lacks a handful of things in the Objective-C project.

Sorry that I can't provide a concrete answer, but I can say that I have no interest in the Objective-C project any more.
