### ISSUE TITLE
GPUImage2 example for android?

### ISSUE THREAD

**Issue by amits180891** [BradLarson/GPUImage2#222]
Hello Sir,

i have search a lot for Android but not get exact example like GPUImage2. 

can you please suggest me for android how can i achieve following filters for Android apps:
1. Harris Corner Detection Filter
2. Noble Corner Detection Filter
3. ShiTomasi Feature Detection Filter.

**Comment by zubco** [comment]
@amits180891 you can find all shaders in "GPUImage2/framework/Source/Operations/Shaders/"

HarrisCornerDetector_GL.fsh (or GLES)
NobleCornerDetector_GL.fsh (or GLES)
ShiTomasiFeatureDetector_GL.fsh (or GLES)

All mentioned filters work is done by this shaders, respectively.

**Comment by BradLarson** [comment]
This is an iOS / Mac / Linux project. If and when Swift becomes a viable language on Android, I may port this over. Until then, you can look at the shaders themselves and roll your own version of this natively.
