### ISSUE TITLE
failed in compiling  Argument passed to call that takes no arguments

### ISSUE THREAD

**Issue by steve21124** [BradLarson/GPUImage2#3]
Pipeline.swift:97:29: Argument passed to call that takes no arguments

`
public func generate() -> AnyGenerator<(ImageConsumer, UInt)> {
        var index = 0
        
        return AnyGenerator { () -> (ImageConsumer, UInt)? in
            if (index >= self.targets.count) {
                return nil
            }
            
            while (self.targets[index].value == nil) {
                self.targets.removeAtIndex(index)
                if (index >= self.targets.count) {
                    return nil
                }
            }
            
            index += 1
            return (self.targets[index - 1].value!, self.targets[index - 1].indexAtTarget)
        }
    }

`

**Comment by BradLarson** [comment]
What version of Xcode / Swift are you building this with? I've targeted this at Xcode 7.3 / Swift 2.2 as the current stable releases.

**Comment by steve21124** [comment]
thanks for the info. I will upgrade mine to Xcode 7.3 then. I am using Xcode  7.2.1
