### ISSUE TITLE
Runtime error in func addSource(_:) of ImageConsumer extension

### ISSUE THREAD

**Issue by strawnut** [BradLarson/GPUImage2#304]
Hi.
I tried to build for FilterShowcase example target.
The build is successful but, when I select something effect from list, then runtime error triggered.

![스크린샷 2019-09-09 오후 2 31 03](https://user-images.githubusercontent.com/19323832/64505498-04cc9f80-d30f-11e9-8c15-9bbe0f03445f.png)

77 to 79 line is that I added test codes.
Yes. The codes is fool. we can expect that is always successful.
However, in the runtime, _self_ does not adopt ImageConsumer.
Eventually, it is triggered runtime error at 77 line without special error message.

I can't undersetand, what is the matter?

**Comment by BradLarson** [comment]
Something sounds like it's broken in your compiler / toolchain / Xcode version:

<img width="530" alt="Screen Shot 2019-09-11 at 2 29 43 PM" src="https://user-images.githubusercontent.com/954279/64728495-b2bb8380-d4a0-11e9-8202-7576600f52f6.png">

This all works just fine here.
