### ISSUE TITLE
Camera continues to call cameraOutput after stopCapture

### ISSUE THREAD

**Issue by mikebikemusic** [BradLarson/GPUImage2#31]
If you have benchmarking turned on, you can see in the logs that frames are still coming in after calling stopCapture. Even without benchmarking, targets are being given the frames to process.  While in this state, it is unsafe to nil the camera instance, as the deinit will be done without stopping captureOutput.

**Comment by jaywardell** [comment]
In Camera.swift:277

```
    public func stopCapture() {
        if (!captureSession.isRunning) {
            captureSession.stopRunning()
        }
    }

```

Could it be as simple as changing that to
```        
        if (captureSession.isRunning) {
```

**Comment by BradLarson** [comment]
That'd be silly. Who would make a mistake like that? Certainly not me.

This should be fixed in both the swift3 and master branches. Thanks for pointing it out.
