### ISSUE TITLE
Value of type 'AVCaptureVideoDataOutput' has no member 'availableVideoPixelFormatTypes' after update Xcode12

### ISSUE THREAD

**Issue by wuyy** [BradLarson/GPUImage2#321]
What should I replace this property？

![75DEDE51-E27D-4070-84C6-2B07ABF8847C](https://user-images.githubusercontent.com/6121255/93427403-59c2ce80-f8f0-11ea-8b1d-a9d3adbaab46.png)

**Comment by Darwel** [comment]
It still works for me.Xcode 12

**Comment by geoffhufford** [comment]
I have the same issue. Just updated to Xcode 12. 

Error building for iOS, no error building MacOS. FilterShowcase iOS example project will demonstrate the error.

**Comment by Darwel** [comment]
It should be a bug of AVFoundation iOS 14 Simulator framework. Use iOS Device.

**Comment by Darwel** [comment]
Or use [kCVPixelFormatType_420YpCbCr8BiPlanarFullRange] for iOS simulator. 
iOS 13.7 iPhone 11 simulator works for me.

**Comment by babucha** [comment]
```
if captureAsYUV {
            supportsFullYUVRange = false
            #if targetEnvironment(simulator)
            let supportedPixelFormats = [kCVPixelFormatType_420YpCbCr8BiPlanarFullRange]
            #else
            let supportedPixelFormats = videoOutput.availableVideoPixelFormatTypes
            #endif
            for currentPixelFormat in supportedPixelFormats {
                if ((currentPixelFormat as NSNumber).int32Value == Int32(kCVPixelFormatType_420YpCbCr8BiPlanarFullRange)) {
                    supportsFullYUVRange = true
                }
            }
```
...
