### ISSUE TITLE
HighlightShadowTintFilter does not work

### ISSUE THREAD

**Issue by c060604** [BradLarson/GPUImage2#33]
I use the HighlightAndShadowTint filter and change value of the shadowTintIntensity property, but nothing happen.

`
    
    
    override func loadView() {
        super.loadView()
        
        picture = PictureInput(image: UIImage(named: "WID-small.jpg")!)
        filter = HighlightAndShadowTint()
        picture --> filter --> renderView
        picture.processImage()
    }
    
    @IBAction func updateValue(sender: AnyObject) {
        filter.shadowTintIntensity = shadowIntensitySlider.value
        picture.processImage()

        print(filter.shadowTintIntensity)
    }
`

**Comment by BradLarson** [comment]
It looks like there were an incorrect number of color components in the shader on the iOS side. This should be fixed in the latest commit.

**Comment by c060604** [comment]
Thank you. I found that the other properties do not work except the highlightTintIntensity property.

**Comment by BradLarson** [comment]
Is this true even with the code I committed today?

**Comment by c060604** [comment]
Good! I pull the newest code and it works.

HighlightShadowTint_GLES.fsh
`uniform highp vec3 shadowTintColor;
uniform highp vec3 highlightTintColor;
`

Now the type of shadowTintColor property is vec3. Can I change the alpha value?

**Comment by BradLarson** [comment]
Not in the current code, which uses just the RGB components for performance. If it's important enough that this be done, the shader and matching filter could be modified to use the full four color components, but I've not done that by default in color inputs to make things faster in the majority of cases.
