### ISSUE TITLE
take care of swift 3

### ISSUE THREAD

**Issue by minamichel17** [BradLarson/GPUImage2#36]
hi brad thanks for your objective c i worked with it alot please take care of swift 3 and ios 10 in this version thanx for your gr8 help

**Comment by TheDarkCode** [comment]
I'm have been working on a fork of GPUImage2 converted to Swift 3 for iOS 10, so I may put it up later.

**Comment by BradLarson** [comment]
I'll be doing this as a "swift3" branch, since many people will need the Swift 2.2 code until Swift 3 is in a stable Xcode. Don't worry about porting this over, I'll take care of that while working on any renaming that might be needed to match the Swift 3 API guidelines.

**Comment by BradLarson** [comment]
There is now a "swift3" branch that should have the iOS and Mac projects and sample applications converted to Swift 3:

https://github.com/BradLarson/GPUImage2/tree/swift3

I'll most likely have to keep this in a separate branch until Xcode 8 can deploy to the App Store.

**Comment by minamichel17** [comment]
Thanx brad alot

Best regards
Mina michel

**Comment by TheDarkCode** [comment]
Awesome. Thanks again, Brad.
