### ISSUE TITLE
Swift 3 ->OperationGroup.swift  error

### ISSUE THREAD

**Issue by zhiblin** [BradLarson/GPUImage2#55]
Xcode 8.0 beta 5 (8S193k)
GPUImage2/framework/Source/OperationGroup.swift:16:78: Expected type

GPUImage2/framework/Source/OperationGroup.swift:17:32: Argument passed to call that takes no arguments
GPUImage2/framework/Source/OperationGroup.swift:16:78: Expected ',' separator

**Comment by BradLarson** [comment]
Is this in the swift3 branch? The swift2 branch hasn't been tested for compatibility with Swift 2.3 in the betas, and is intended for backwards compatibility with Xcode 7 until 8 is final.

The swift3 branch is a bit of a mix right now, as I'm having to use the latest OSS snapshot compiler with Xcode 8 beta 1 until some issues are fixed on the Mac side.

**Comment by zubco** [comment]
Right, it is on swift3 branch.

The section of code:
`public func configureGroup(_ configurationOperation:(_ input:ImageRelay, _ output:ImageRelay) -> ()) {
        configurationOperation(inputImageRelay, outputImageRelay)
}`

Should be updated to:
`    public func configureGroup(_ configurationOperation:(input:ImageRelay, output:ImageRelay) -> ()) {
        configurationOperation(input:inputImageRelay, output:outputImageRelay)
    }
`

**Comment by zhiblin** [comment]
OK!  Thanks
