### ISSUE TITLE
simpleVideoRecorder example not working

### ISSUE THREAD

**Issue by longsangstan** [BradLarson/GPUImage2#59]
Hi,

I found that the simpleVideoRecorder example is not working.

When I press the record button, the screen flashes for one time and then nothing happens - not recording, button label didn't change to "Stop", no video found in photo library. My device is iPad mini 2. 
Here is the screencast: https://streamable.com/96v2

After some logging I found that when the record button is pressed, both the `if` part and `else` part of the `capture` function are called. Refer to below:

```
@IBAction func capture(sender: AnyObject) {
        
        print("CLICKED") // Called
        
        if (!isRecording) {
            do {
                self.isRecording = true
                let documentsDir = try NSFileManager.defaultManager().URLForDirectory(.DocumentDirectory, inDomain:.UserDomainMask, appropriateForURL:nil, create:true)
                let fileURL = NSURL(string:"test.mp4", relativeToURL:documentsDir)!
                do {
                    try NSFileManager.defaultManager().removeItemAtURL(fileURL)
                } catch {
                }
                
                movieOutput = try MovieOutput(URL:fileURL, size:Size(width:480, height:640), liveVideo:true)
                camera.audioEncodingTarget = movieOutput
                filter --> movieOutput!
                movieOutput!.startRecording()
                (sender as! UIButton).titleLabel?.text = "Stop"
                
                print("RECORDING!") // Called
                
            } catch {
                
                print("ERROR!!!!!") // Not Called
                
                fatalError("Couldn't initialize movie, error: \(error)")
            }
        } else {
            movieOutput?.finishRecording{
                self.isRecording = false
                dispatch_async(dispatch_get_main_queue()) {
                    (sender as! UIButton).titleLabel?.text = "Record"
                    
                    print("STOPPPPPPP!!!") // Called, why?
                }
                
                print("STOPPED!!!") // Called, why?
                
                self.camera.audioEncodingTarget = nil
                self.movieOutput = nil
            }
        }
    }
```

Has anyone had the same problem? Any idea how to fix it?

Stan

**Comment by BradLarson** [comment]
It doesn't store the video in the photo library. It stores the video locally in the application's documents directory. You can look for it there.

**Comment by longsangstan** [comment]
Hi Brad,

I cannot find the video in the application's directory as well, I think it is because the video is not recorded?

When I press the "record" button, the screen just flashes, and the button label did not change to "stop". Like this: https://streamable.com/96v2

As stated above, it looks like the `movieOutput?.finishRecording` part is immediately called after I press the "record" button.

Thanks.
