### ISSUE TITLE
Xcode 8 Compatibility

### ISSUE THREAD

**Issue by Aytharn** [BradLarson/GPUImage2#62]
GPUImage is not compatible with Xcode 8 using Swift 3.0.

Critical incompatibilities are still raised by setting the new Swift Legacy mode parameter in Xcode, if you try to use the automatic problem solver, the project will run but crash on start.

**Comment by BradLarson** [comment]
Is this with the swift3 branch? The main code is Swift 2, supporting the stable shipping releases of Xcode, where the swift3 branch is where support for Xcode 8 is being maintained.
