### ISSUE TITLE
filterWithPipeline always fails with nil

### ISSUE THREAD

**Issue by cloke** [BradLarson/GPUImage2#71]
OutputImage is always created as nil and the value is set in a callback. The method returns a forced unwrapped optional that will always return nil and crash. 

https://github.com/BradLarson/GPUImage2/blob/9f7c141955497ab4dadf27ea3821ce1b893073ae/framework/Source/iOS/PictureOutput.swift#L106

My hack to fix it is to always return self, but I am not familiar enough with the library to know if this is a correct approach.

**Comment by BradLarson** [comment]
imageAvailableCallback is triggered on the next execution of newFramebufferAvailable(), which is kicked off synchronously by the line

    picture.processImage(synchronously:true)

The block will complete execution as a result, and should have a non-nil value in outputImage. If this didn't work, at least one of the example applications would fail during synchronous image processing.

What cases are you seeing this fail for? Is it possible there's a bad input image?

**Comment by cloke** [comment]
This started happening when I updated to master about 3 days ago, before that I never saw the issue. After pulling in master it was happening in all situations. Its possible it is related to my general swift 3 update. I'll back out my hack and see if I can get some more concrete details.

**Comment by cloke** [comment]
I was able to track this down to the fact that I am doing something like this in my code:

 output.imageAvailableCallback = callback

Which is essentially overwriting the callback in the framework. I had been using the Swift 2 version of GPUImage2 and this didn't seem to be a problem. Is there a more appropriate way to be notified when the output image is available?

**Comment by cloke** [comment]
So it turns out I was sort of mixing two concepts together in the wrong way. I was using the filterWithPipeline extension and then also processing things unintentionally a second time with extra code. Fixing this has made my image render time drastically faster. Whats weird is the broken code worked on swift 2 as the app has been in production for almost 4 months, but with swift 3 the problem was front and center.
