### ISSUE TITLE
Package iOS and OSX as a single, universal framework?

### ISSUE THREAD

**Issue by maxcan** [BradLarson/GPUImage2#8]
I'm not sure how feasible this is, but for one of my use cases (where there is a lot of sharing between iOS and OSX), it would be nice to have a single universal framework along the lines of this: http://colemancda.github.io/programming/2015/02/11/universal-ios-osx-framework/

**Comment by BradLarson** [comment]
It's a concept I kicked around, but I decided to go with the setup I knew worked. You originally couldn't have both in a single project, but they added capabilities over the last few years to make that possible. I never went back and tried to do this, even the one-project-two-targets thing.

This particular approach would seem to fall down in a few cases where I need to have different files belonging to the Mac and iOS projects. I don't think you'd have a way of differentiating them without multiple targets.

**Comment by maxcan** [comment]
Fair enough.. I'll close this.
