### ISSUE TITLE
first frame is black when i record video using Movieoutput

### ISSUE THREAD

**Issue by WorthyZhang** [BradLarson/GPUImage2#80]
I tested SimpleVideoRecorder demo,when i touched record button ,the renderview flashed with black frame. After i saved the output video,the first frame of video is dark or black.

**Comment by dvma04** [comment]
Hi. @WorthyZhang  i had similar problem but with white frame in the beginning of the file in iOS. I've changed a bit logic of start the output session. You can try version from my fork. If this will help you i could provide a PR. I was thinking that this is just my little problem.

**Comment by WorthyZhang** [comment]
@dvma04  I solved the the problem by calling  addAudioInputsAndOutputs() method, maybe it will help you.

**Comment by hoangelec** [comment]
Can you pls show me where you call the addAudioInputsAndOutputs() method?
