### ISSUE TITLE
Can not import GPUImage

### ISSUE THREAD

**Issue by FogiDestructor** [BradLarson/GPUImage2#87]
I've imported the GPUImage 2 Framework on my Swift 3 project and when I try to use it's types, it gives me as undeclared type. I'm a beginner in Swift programing and in working with Xcode. Maybe I've imported the Framework wrong, I don't really know.
This problem appeared as I am converting an app from Swift 2 to Swift 3.

**Comment by zubco** [comment]
@FogiDestructor Try to follow described steps from [Readme - Using GPUImage in an Mac or iOS application](https://github.com/BradLarson/GPUImage2#using-gpuimage-in-an-mac-or-ios-application).
If you did it all right, you shouldn't have any issues ;)
Cheers.

**Comment by BradLarson** [comment]
The current version of GPUImage in the repository is built around Swift 3. If you are not using that, you will have problems. Beyond that, I'm not sure what errors you're seeing, so I can't provide further help.

**Comment by FogiDestructor** [comment]
![screen shot 2016-11-10 at 8 44 11 pm](https://cloud.githubusercontent.com/assets/23381963/20189578/7cdc0eaa-a786-11e6-845e-f842457ee42a.png)

Here's my issue

**Comment by zubco** [comment]
@FogiDestructor [GPUImage](https://github.com/BradLarson/GPUImage) & [GPUImage2](https://github.com/BradLarson/GPUImage2) are not using absolutely same types (GPUImageMovieWriter is from GPUImage). You can't just interchange between this 2 frameworks in the same project without code modifications ;)

**Comment by FogiDestructor** [comment]
@zubco Thank you. Is the there an analog for GPUImageMovieWriter on GPUImage2 or a list of all types. 
Sorry for this question, I know for someone those could be easy, but I am on really early stage and don't have some who could guide or help me.
Thank you))

**Comment by nateemma** [comment]
There is a class MovieOutput.swift in the Outputs folder. If that doesn't work, I guess you could use the Objective C version and just create a bridging header for it (XCode will do this for you).
