### ISSUE TITLE
Can we use GPUImage2 in an Objective-C project?

### ISSUE THREAD

**Issue by traic** [BradLarson/GPUImage2#96]
I'm migrating from GPUImage to GPUImage 2 because there is a nasty memory leak I could not fix in the OpenGL texture context calls. I tried importing the SWIFT project into an Objective-C project, but noticed in the bridge header of the Camera class, that the init method was not translated properly:

SWIFT_CLASS("_TtC8GPUImage6Camera")
@interface Camera : NSObject <AVCaptureVideoDataOutputSampleBufferDelegate, AVCaptureAudioDataOutputSampleBufferDelegate>
@property (nonatomic) BOOL runBenchmark;
@property (nonatomic) BOOL logFPS;
- (void)captureOutput:(AVCaptureOutput * _Null_unspecified)captureOutput didOutputSampleBuffer:(CMSampleBufferRef _Null_unspecified)sampleBuffer fromConnection:(AVCaptureConnection * _Null_unspecified)connection;
- (void)startCapture;
- (void)stopCapture;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

Will this work?

**Comment by traic** [comment]
http://stackoverflow.com/questions/26470771/swift-init-not-visible-in-objecitve-c

Read that SWIFT cannot bridge optional types, assuming this was not built to provide backwards compatibility.

**Comment by BradLarson** [comment]
The goal of the project has been a pure Swift reimplementation, and no consideration has been given to interfacing with older Objective-C code. Many of the types have no clean mapping back to Objective-C, so it will be difficult to use this in that direction.
