### ISSUE TITLE
Motion Detection in SWIFT

### ISSUE THREAD

**Issue by jscardona12** [BradLarson/GPUImage2#97]
hi, how can i use Motion Detection in Swift??

**Comment by BradLarson** [comment]
The MotionDetector has you set a callback block called `motionDetectedCallback` that will provide you with the normalized centroid and magnitude of the motion that is detected in the scene. It's a crude measure, simply taking pixel differences between frames.

This callback will be called on every video frame that passes through the pipeline. The FilterShowcase shows how to use this to draw a box on the screen.

**Comment by jscardona12** [comment]
Hi Brad
I don't know why doesn't enter to the callback, can you tell me what i'm doing wrong. thank you
 override func viewDidLoad() {
        super.viewDidLoad()
        
        do {
            camera = try Camera(sessionPreset:AVCaptureSessionPreset640x480)
            camera.runBenchmark = false
            camera.delegate = self
            md.motionDetectedCallback = { motionCentroid,strength in
                print("XXXXXXXXXXX")
                print(motionCentroid.x)
                print("YYYYYYYYYYY")
                print(motionCentroid.y)
                var motionBoxWidth:CGFloat
                motionBoxWidth = CGFloat(1500.0)*CGFloat(strength)
                var viewBounds: CGSize
                viewBounds = self.renderView.bounds.size
                var fBounds:CGRect
                fBounds = CGRect(x: round(viewBounds.width * CGFloat(motionCentroid.x) - motionBoxWidth / 2.0), y: round(viewBounds.width * CGFloat(motionCentroid.y) - motionBoxWidth / 2.0), width: motionBoxWidth, height: motionBoxWidth)
                
                var lines = [Line]()
                lines = lines + self.faceLines(fBounds)
                
                self.lineGenerator.renderLines(lines)
            }
            camera --> saturationFilter --> blendFilter --> renderView
            lineGenerator --> blendFilter
            shouldDetectFaces = faceDetectSwitch.isOn
            
            camera.startCapture()
            

        } catch {
            fatalError("Could not initialize rendering pipeline: \(error)")
        }
    }

**Comment by BradLarson** [comment]
Near as I can tell, `md` isn't part of your filter chain, so it's never receiving frames. You need a 

    camera --> md 

or the like in there somewhere.

**Comment by jscardona12** [comment]
Thankyou very much Brad.
I'm going to bother you the last time. know the filtre makes that the image becomes a color substractor, how can i revert this?

Thankyou for your time.

**Comment by BradLarson** [comment]
Just don't pipe the output from the motion detector anywhere. Set an input to it, but don't set an output. Rely entirely on the callback block.

**Comment by SoundandStuff** [comment]
Hi @jscardona12 
Did you ever get the motion detector to work without the output going to the renderView? For what ever odd reason, the callback only work if it is camera --> motiondetector --> renderView. 
If it is just camera --> motiondetector it doesn't seem to respond.

**Comment by SoundandStuff** [comment]
This works ....

` do {
            
            
            
            camera = try Camera(sessionPreset:AVCaptureSessionPresetPhoto, location:.backFacing)
            
            camera.runBenchmark = true
            
            camera --> motion --> renderView
            
                        
            camera.startCapture()
 
            var motionvar = 0
            var zeromotion = 0
            var motiondetected = false
            
            
            
            motion.motionDetectedCallback = { motionCentroid,strength in
                print("x\(motionCentroid.x)")
                print("y\(motionCentroid.y)")
            }`


This does not call the motion
`

        do {
            
                        
            camera = try Camera(sessionPreset:AVCaptureSessionPresetPhoto, location:.backFacing)
            
            camera.runBenchmark = true
            
            camera --> motion
            camera --> renderView    
            
                        
            camera.startCapture()
            var motionvar = 0
            var zeromotion = 0
            var motiondetected = false
     
            motion.motionDetectedCallback = { motionCentroid,strength in
                print("x\(motionCentroid.x)")
                print("y\(motionCentroid.y)")
            }


`

**Comment by dimohamdy** [comment]
How i can use MotionDetector with  didCaptureBuffer(_ sampleBuffer: CMSampleBuffer) ?
