### ISSUE TITLE
Create lookup image

### ISSUE THREAD

**Issue by gkye** [BradLarson/GPUImage2#99]
This might be a bit off off topic but I was wondering how to generate a look up image using an `.atn` in photoshop similar to the `AmatorkaFilter` in photoshop?
![filterme_part2_originallut](https://cloud.githubusercontent.com/assets/14007152/21266905/143cf132-c376-11e6-9053-d03a1887473b.png)

**Comment by zubco** [comment]
@gkye Idk about `.atn`, but you should use `GPUImage2/framework/Source/Operations/LookupImages/lookup.png` image as a template.
1. Open it in Photoshop
2. Apply your effect to it.
3. Export it.
4. Ready to use as a Lookup image in GPUImage.

Cheers.

**Comment by gkye** [comment]
Thanks for the help
